# What program(s) have to be built
PROGRAMS = ex4.2

# Dependencies for the program(s) to build
ex4: ../common/remregs.o ../common/wperror.o ../common/robot.o ../common/utils.o ex4.2.o

# Includes the common Makefile with the various rules
include ../common/Makefile.inc
